const constants = {
  GET_ORDER_PER_DAY_AWAITING: "GET_ORDER_PER_DAY_AWAITING",
  GET_ORDER_PER_DAY_SUCCESS: "GET_ORDER_PER_DAY_SUCCESS",
  GET_ORDER_PER_DAY_ERROR: "GET_ORDER_PER_DAY_ERROR",

  GET_INCOME_PER_DAY_AWAITING: "GET_INCOME_PER_DAY_AWAITING",
  GET_INCOME_PER_DAY_SUCCESS: "GET_INCOME_PER_DAY_SUCCESS",
  GET_INCOME_PER_DAY_ERROR: "GET_INCOME_PER_DAY_ERROR",

  GET_PROFIT_PROFIT_DAY_AWAITING: "GET_PROFIT_PER_DAY_AWAITING",
  GET_PROFIT_PER_DAY_SUCCESS: "GET_PROFIT_PER_DAY_SUCCESS",
  GET_PROFIT_PER_DAY_ERROR: "GET_PROFIT_PER_DAY_ERROR",

  UPDATE_TODO_STATUS_ERROR: "UPDATE_TODO_STATUS_ERROR",
  UPDATE_TODO_STATUS_SUCCESS: "UPDATE_TODO_STATUS_SUCCESS",

  DELETE_ALL_TODOS_ERROR: "DELETE_ALL_TODOS_ERROR",
  DELETE_ALL_TODOS_SUCCESS: "DELETE_ALL_TODOS_SUCCESS",

  LOADING_START: "LOADING_START",
  LOADING_END: "LOADING_END",
};

export default constants;
