const constants = {
  GET_ORDER_PER_DAY_SUCCESS: "GET_ORDER_PER_DAY_SUCCESS",

  GET_INCOME_PER_DAY_SUCCESS: "GET_INCOME_PER_DAY_SUCCESS",

  GET_PROFIT_PER_DAY_SUCCESS: "GET_PROFIT_PER_DAY_SUCCESS",

  GET_TOP_TEN_ITEMS_SUCCESS: "GET_TOP_TEN_ITEMS_SUCCESS",

  GET_PROFIT_PRESENTAGE_SUCCESS: "GET_PROFIT_PRESENTAGE_SUCCESS",

  LOADING_START: "LOADING_START",
  LOADING_END: "LOADING_END",

  ERROR: "ERROR",
};

export default constants;
